### ISSUE TITLE
Instructions to use the API are hard to understand

### ISSUE THREAD

**Issue by armenzg** [mozilla-iam/cis#397]
I've tried to follow the instructions and the tests but I could not figure it out.

If there was a demo app with an auth0 client (only public scopes) that can show the public data it might go a long way to get users started.
It's hard to have to wait for the Service now request to be processed before I can try anything.

**Comment by gdestuynder** [comment]
while we can't issue "public" credentials, it's likely that we have some unauth-ed routes in the future as the login (NLX) needs one of these, which can be used to at least ping the API and get something back (Im guessing we could also support an actual PING for unauthenticated service checks)

Regarding the credential issuance, indeed, this is how it currently works as access has to be vetted.

Regarding the doc, it's fairly new but I would welcome some direct feedback (or changes of course) on the sections that you find difficult so that we can improve them for the next user

**Comment by andrewkrug** [comment]
I'll just echo what @gdestuynder has said here.  This is a primarily authenticated API full of sensitive data.  Most of the features will be behind some credential vending process: oauth, scopes, etc.  Our normal turnaround for service now requests is usually around one business day in normal circumstances.
