### ISSUE TITLE
Grant AWS IAM access to devs

### ISSUE THREAD

**Issue by johngian** [mozilla-iam/cis#5]
- [x] Decision on model for delegated access to parsys.  Recommendation on scoping.
- [x] Update IAM managed policy granting access
- [ ] Deliver document to tasos and nemo with instructions on deploying the apex project as a developer.

**Comment by andrewkrug** [comment]
I've been working on this stuff.  Effectively I now have two cloudformation templates:

1. Creates the roles for all the stream processors ( these are in lambda and probably managed by APEX ) 
2. Creates DynamoDB and Kinesis / Sets up the hooks for DynamoDB streams as well.

The question I have about this is:

Do we need to delegate access to parsys devs in our infosec-dev account and infosec-prod account to work on this or can we dev in two separate accounts without blockers?

Ultimately I think change integration service both dev and prod should likely live in it's own AWS account since we will have lambda functions invoking other lambdas and will need a shared space for parsys and infosec to iterate together as the service grows.  The service will also contain lots of sensitive data that not all parties need access to for day to day.  

It is technically possible to achieve isolation and delegated access with IAM roles and constraints inside of a shared account as well but it seems unnecessary if we agree the service should have it's own account.

**Comment by gene1wood** [comment]
We should weigh the cost of creating isolated access within an account against the cost of maintaining an additional AWS account over time

**Comment by andrewkrug** [comment]
@gene1wood I agree.  How do we do that and what would be the criteria we would use to assess cost here?

**Comment by jeffbryner** [comment]
I think we default to one account for the reasons mentioned unless we find a technical reason we cannot. I'm in favor of one well maintained thing rather than several semi-maintained things.

**Comment by gene1wood** [comment]
>  How do we do that

This probably involves a bit of thinking about what the policy would look like to enable users the abilities they need and prevent them from having rights to affect resources for services that they don't need.

The most interesting part of this is likely cases where users need rights to do things in the AWS IAM product so as to prevent them from having rights to create roles or iam:passrole for all roles, either of which grant them effective `*:*`

> what would be the criteria we would use to assess cost here?

I'm just imagining a rough estimation of the one time effort of making the policy and tags and a rough estimation of what overhead is for managing additional accounts.

**Comment by gene1wood** [comment]
To the specific challenges of granting users `iam:CreateRole` one approach would be to have us (where us is some administrative group of people who can do things across the whole account, which at the moment is the whole infosec team) create the roles that are needed as well as the role granting the user or instance the `iam:PassRole` permission but resource constrained to just the roles we've created.

**Comment by gene1wood** [comment]
More generally, I think we should have the capability to do granular access control of our services within our team and a working approach to this with CIS could just be reused across our account. For example, I shouldn't have rights to affect the mig server infrastructure because I don't work on mig server stuff, but I do.

Additionally the reference model that we would have here could be used by other teams as well.

But again, these details that I'm calling out are all secondary to a frank assessment of the costs in time. If it's a large effort to make these policies and tags and creating a new account and managing it over time isn't that much effort, then we should just create another account.

**Comment by andrewkrug** [comment]
@gene1wood I don't think those iam: permissions I mentioned are necessary to do the CIS developer role.  It's more of a nice to have to allow for rapid iteration without escalating.  The developer role for apex framework+cis could be created to use tag based constraints and static pre provisioned function roles.  We would all just need a shared agreement that any time those roles need modified or a new role need be created that a developer working on CIS would escalate to an infosec team member.

**Comment by andrewkrug** [comment]
@gene1wood :  

> If it's a large effort to make these policies and tags and creating a new account and managing it over time isn't that much effort, then we should just create another account.  

Does the adoption of AWS Organizations change any of that overhead for us?

**Comment by gene1wood** [comment]
> We would all just need a shared agreement that any time those roles need modified or a new role need be created that a developer working on CIS would escalate to an infosec team member.

A good point, having this access model would be good but it would suck if it reduced development inertia.

> Does the adoption of AWS Organizations change any of that overhead for us?

It will reduce the [overhead on the IT side of provisioning the new account](https://mana.mozilla.org/wiki/display/EA/AWS+Account+Opening+process) (which is currently manual) in regards to the AWS interaction. There's still google groups, cloudhealth, asap, service now, etc stuff to do.

I've not yet seen what the AWS Organizations API driven account creation stuff is but by the description it should reduce their (IT's) workload a lot with new accounts.

**Comment by andrewkrug** [comment]
> A good point, having this access model would be good but it would suck if it reduced development inertia.

^^ This is my primary concern.  At least while we're prototyping.  In a perfect world if time and cost were no object the entire team would have one sandbox account ( hopefully one that is thrown away ) that everyone works in until the architecture is solidified and can be moved to a more mature model like the one you've described here.  

We're not blocked really right now but will need to figure out how parsys/infosec are working on this set of things soon-ish.  ( Proposed model needs to be realized by the beginning of Sprint 8 )

Also, since timezones are a factor for us I want to come up with a low friction model.

**Comment by andrewkrug** [comment]
@gene1wood 

I've got most of a setup in place for allowing parsys folks access to only CIS resources in the infosec-dev account.  

However, it would appear for lambda, kinesis, and dynamodb resource tagging may not work quite the same way as it does with EC2 resources.  

See:
http://docs.aws.amazon.com/lambda/latest/dg/lambda-api-permissions-ref.html

I'd appreciate a scoping recommendation on how I might move forward with using the tag based approach.
