### ISSUE TITLE
Remove duplicate code

### ISSUE THREAD

**Issue by johngian** [mozilla-iam/cis#55]
Having duplicate code is really bad:

* Error prone since you need to apply changes to all the files one by one 
* Its a maintenance hell because you need to keep track of the same copy in multiple different paths

Let's deduplicate:

* utils.py
* clean.sh
* requirements.txt

**Comment by andrewkrug** [comment]
@johngian clean.sh is unique per serverless_function as it deletes any files that aren't whitelisted as part of the core code.  Though it is very very similar it is the one of these things that is likely not totally duplicated across the function code base.  

Agree on utils.py and requirements.txt being central.  Can actually move requirements.txt up to the project level of cis_functions and then call that in the config instead of how it is now.

**Comment by andrewkrug** [comment]
Everything except clean.sh has been taken care of.
